"""
Simulates ESP8266 telemetry for testing the dashboard end to end.
Sends fake real-motor readings to the Flask server at a steady interval,
with a simulated load increase partway through to trigger an anomaly.

Run this WHILE flask_server.py is already running.

    python3 test_feed.py
"""
#this was generated by ai just to test the dashboard 
import time
import requests

SERVER_URL = "http://127.0.0.1:5000/telemetry"
INTERVAL = 0.3  # seconds between sends -- matches a realistic ESP8266 rate

NOMINAL_RPM = 65.0
NOMINAL_CURRENT = 0.12
VOLTAGE = 12.0

TOTAL_SAMPLES = 100
LOAD_STARTS_AT = 40   # sample index where we simulate a friction/load event
LOAD_ENDS_AT = 70


def main():
    print(f"Sending {TOTAL_SAMPLES} samples to {SERVER_URL} every {INTERVAL}s...")
    for i in range(TOTAL_SAMPLES):
        if LOAD_STARTS_AT <= i < LOAD_ENDS_AT:
            # simulate real motor slowing down / drawing more current under load
            # (server's virtual twin doesn't know about this load unless you also
            # send load_torque -- so this naturally creates a Real vs Virtual gap,
            # which is exactly what your anomaly detector should catch)
            payload = {"rpm": 40.0, "current": 0.35, "voltage": VOLTAGE}
            tag = "LOAD EVENT"
        else:
            payload = {"rpm": NOMINAL_RPM, "current": NOMINAL_CURRENT, "voltage": VOLTAGE}
            tag = "nominal"

        try:
            resp = requests.post(SERVER_URL, json=payload, timeout=1.0)
            print(f"[{i+1}/{TOTAL_SAMPLES}] {tag} -> {resp.status_code} {resp.json()}")
        except requests.RequestException as e:
            print(f"[{i+1}/{TOTAL_SAMPLES}] ERROR: {e}")

        time.sleep(INTERVAL)

    print("Done.")


if __name__ == "__main__":
    main()
